nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  ix:
    npmRegistryServer: "http://localhost/verdaccio"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.9.1.cjs
