nodeLinker: node-modules
npmRegistryServer: "http://localhost/verdaccio"
enableStrictSsl: false

npmScopes:
  ix:
    npmRegistryServer: "http://localhost/verdaccio"

unsafeHttpWhitelist:
  - "127.0.0.1"
  - "localhost"
  
yarnPath: .yarn/releases/yarn-4.9.1.cjs
