nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - "localhost"

npmScopes:
  ix:
    npmRegistryServer: "http://localhost:4873"
    npmAuthToken: "fake-token"
