nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

npmRegistryServer: "http://localhost/verdaccio/"

unsafeHttpWhitelist:
  - "localhost"

npmScopes:
  ix:
    npmRegistryServer: "http://localhost/verdaccio/"
    # npmAuthToken: "fake-token"
