apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017         # Cluster-internal port
      targetPort: 27017   # MongoDB container port
      nodePort: 32017     # Exposed port on your localhost (Kind node)
      protocol: TCP
