apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: laniakea-mongodb
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: local
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: local
          ports:
            - containerPort: 27017
              name: mongo
          args: ["--nojournal"]  # reduces disk usage in dev
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: mongo-storage
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: mongo-pvc
