---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verdaccio-storage-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /var/lib/verdaccio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-storage-pvc
  namespace: laniakea-local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
  volumeName: verdaccio-storage-pv
