services:
  # PostgreSql
  laniakea-db:
    image: postgres:14.13-alpine3.20
    container_name: laniakea-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=laniakea-test
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  # MongoDB
  laniakea-mongodb:
    image: mongo:7.0.12
    container_name: laniakea-mongodb
    volumes:
      - mongo-data:/data/db
      # -./database/mongodb/init.js:/docker-entrypoint-initdb.d/init-mongo-db-with-collections.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=laniakeatestdb
    ports:
      - "27017:27017"
    command: --quiet
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5





  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # Cloud Stacks
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # Google Cloud - Datastore
  laniakea-gcp-datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:392.0.0
    # environment:
    #   - DATASTORE_DATASET=my-project-id
    #   - DATASTORE_EMULATOR_HOST=[::1]:8630
    #   - DATASTORE_EMULATOR_HOST_PATH=[::1]:8630/datastore
    #   - DATASTORE_HOST=http://[::1]:8630
    #   - DATASTORE_PROJECT_ID=my-project-id
    #   - DATASTORE_USE_PROJECT_ID_AS_APP_ID=true
    ports:
      - "8000:8081"
    command: gcloud beta emulators datastore start --project=datastore-wrapper --host-port=0.0.0.0:8081 --project emulator --store-on-disk
    # --no-store-on-disk --use-firestore-in-datastore-mode

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # LOCAL DEVELOPMENT PORPUSE ONLY
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # Nginx Reverse Proxy for local tests
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "31000:31000"  # Map port 31000
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/error502.html:/usr/share/nginx/html/error502.html:ro  # Mount the custom 502 error page
      - ./reverse-proxy/error503.html:/usr/share/nginx/html/error503.html:ro  # Mount the custom 503 error page      

volumes:
  postgres-data:
    name: laniakea-postgres-data
  mongo-data:
    name: laniakea-mongodb-data

networks:
  default:
    name: laniakea-network

    