global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laniakea-mcs-auth'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'laniakea-mcs-logistics'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:3900']