---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: laniakea-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "250"
    extraMounts:
      - hostPath: /etc/security/limits.conf
        containerPath: /etc/security/limits.conf
      - hostPath: /etc/security/limits.d
        containerPath: /etc/security/limits.d
