apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-cmy-apps
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-cmy-backend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-sys-metrics
---
apiVersion: v1
data:
  AUTH_SERVER_HOST: localhost
  AUTH_SERVER_PORT: "50051"
  DATABASE_TYPE: mongodb
  MONGO_AUTH_CN_NAME: authConnection
  MONGO_DB: laniakeatestdb
  MONGO_HOST: laniakea-mongodb
  MONGO_LOGISTICS_CN_NAME: logisticsonnection
  MONGO_PASSWORD: local
  MONGO_PORT: "27017"
  MONGO_USER: local
  NODE_ENV: dev
  TRACK_QRCODE_ENDPOINT: https://www.example.com
kind: ConfigMap
metadata:
  labels:
    env: dev
    silo: community
  name: logistics-config
  namespace: laniakea-cmy-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    createdBy: laniakea-platform
    managedBy: kustomize
  labels:
    env: dev
    module: logistics
    silo: community
    type: backend
  name: deploy-logistics-mcs
  namespace: laniakea-cmy-apps
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mcs-logistics
  template:
    metadata:
      annotations:
        createdBy: laniakea-platform
        managedBy: kustomize
      labels:
        app: mcs-logistics
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: logistics-config
        image: gcr.io/google-samples/microservices-demo/adservice:v0.4.1
        name: mcs-logistics
        ports:
        - containerPort: 9555
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
