apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: laniakea-apps
nameSuffix: -logistics

labels:
  - pairs:
      module: logistics
      silo: community
      type: backend

resources:
  - ../../base

configMapGenerator:
- name: config
  literals:
    - mcs-name=mcs-logistics
    - eng-dhl-name=eng-dhl
    # - module=logistics
    # - silo=community

replacements:
- source:
    kind: ConfigMap
    name: config-logistics
    fieldPath: data.mcs-name
  targets:
    - select:
        kind: Deployment
        name: laniakea-mcs-logistics
      fieldPaths:
        - spec.selector.matchLabels.app
        - spec.template.metadata.labels.app
        - spec.template.spec.containers.[name=mcs].image
        - spec.template.spec.containers.[name=mcs].name
