apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-cmy-apps
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-cmy-backend
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    silo: community
  name: laniakea-sys-metrics
